rollFormula = "2d6"

# Define stats.
[stats]
  cool = "Cool"
  hard = "Hard"
  hot = "Hot"
  sharp = "Sharp"
  weird = "Weird"

# Define attributes.
[attributesTop]
  [attributesTop.armor]
    type = "Number"
  [attributesTop.harm]
    type = "Clock"
    max = 6
  [attributesTop.improvement]
    type = "Xp"
    max = 5
  [attributesTop.customResource]
    type = "Resource"

# Define sidebar details.
[attributesLeft]
  look = "LongText"
  hx = "LongText"

# Define logical groups for moves.
[moveTypes]
  basic = "Basic"
  advanced = "Advanced"

# Define roll result ranges.
[rollResults]
  [rollResults.failure]
    range = "6-"
    label = "Complications..."
  [rollResults.partial]
    range = "7-9"
    label = "Partial success"
  [rollResults.success]
    range = "10+"
    label = "Success!"
  [rollResults.critical]
    range = false
    label = "Critical Success!"